### ISSUE TITLE
Update install instructions for Python 3

### ISSUE THREAD

**Issue by ichilton** [napalm-automation/napalm-salt#68]
Hi!

I think the install instructions in the README should now use python3.

On Debian (buster) at least, I also had to install python3-setuptools, rustic and cargo for it to succeed.

This is what I ended up with:

```
napalm-deps:
  pkg.installed:
    - pkgs:
      - libffi-dev
      - libssl-dev
      - libxslt1-dev
      - python3-dev
      - python3-pip
      - python3-cffi
      - python3-setuptools
      - rustc
      - cargo

napalm-install:
  pip.installed:
    - name: napalm
    - upgrade: False
    - require:
      - pkg: napalm-deps
```
